name: Build and Release APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - run: ./gradlew assembleRelease
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.sha }}
          name: Build ${{ github.sha }}
          artifacts: app/build/outputs/apk/release/app-release.apk
          prerelease: true
